#!/bin/bash

while getopts "la:r:" opt; do
	case $opt in
		l)
			/usr/local/bin/exec l
			exit 0
			;;
		a)
			set -f
			IFS=,
			arg=($OPTARG)
			;;
		r)
			/usr/local/bin/exec r ${OPTARG}
			exit 0
			;; 
		[?])
			echo "Not a valid Option!"
			exit 1;; 
	esac
done

/usr/local/bin/exec a ${arg[@]}

#for val in "${arg[@]}"; do
#	echo $val
#done

exit 0
